language: cpp

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository --yes ppa:kalakris/cmake
  - sudo apt-get update -qq
    #Install and use gcc-4.8 (don't build with gcc-4.6)
    #libstdc++-4.8 is needed by Clang to build too
  - sudo apt-get -qq install g++-4.8 libstdc++-4.8-dev
  - sudo apt-get -qq install cmake
  - sudo apt-get -qq install libprotobuf-dev protobuf-compiler
  - cmake --version
  - export CXX="g++-4.8"

script:
  - cmake .
  - make -j4
  - make test
